spring:
  h2:
    console:
      enabled: true
      path: /h2_admin
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:tcp://localhost/~/test"
    username: "sa"
    password: ""
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      minimum-idle: 5
      max-lifetime: 2400000
      maximum-pool-size: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    properties:
      hibernate.format_sql: true
