server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev, database
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template: true
    cache: false
    check-template-location: true
    mode: HTML5
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: info
    com.springboot.springsecurity: debug